'use client'
import { useState } from 'react'
import { CASES, POSES } from '@/lib/creative-studio/model'
import type { CanvasNode } from '@/lib/creative-studio/model'
import { CATEGORIES, TOOLS } from '@/lib/creative-studio/tools'
import type { Studio } from './use-studio'
import { Icon, IconButton, Picture } from './ui'
import s from './studio.module.css'
export function StudioDrawer({kind,studio,onClose,onTool,onAsset,onUpload,onFocus}:{kind:'tools'|'assets'|'layers';studio:Studio;onClose:()=>void;onTool:(id:string)=>void;onAsset:(node:CanvasNode,reference:boolean)=>void;onUpload:()=>void;onFocus:(ids:string[])=>void}){
  const [search,setSearch]=useState(''),[category,setCategory]=useState('全部'),[assetTab,setAssetTab]=useState('本项目')
  const title=kind==='tools'?'AI 工具箱':kind==='layers'?'画布图层':'素材库'
  const synthetic=(id:string,name:string,url:string):CanvasNode=>({id,name,url,kind:'image',status:'ready',x:0,y:0,width:220,height:293})
  const assets=assetTab==='姿势'?POSES.map(p=>synthetic(p.id,p.name,p.url)):assetTab==='服装成片'?CASES.map((url,i)=>synthetic(`case-${i}`,`童装商拍 ${String(i+1).padStart(2,'0')}`,url)):studio.doc.nodes.filter(n=>n.kind==='image'&&n.status==='ready'&&(assetTab!=='收藏'||n.favorite))
  const filtered=assets.filter(n=>n.name.toLowerCase().includes(search.toLowerCase()))
  return <section className={`${s.drawer} ${kind==='tools'?s.toolDrawer:''}`} data-ui aria-label={title}>
    <header className={s.drawerHeader}><div><span className={s.eyebrow}>{kind==='tools'?'为下一步，找到合适工具':'属于这个创作空间'}</span><h2>{title}</h2></div><IconButton label="关闭抽屉" icon="close" onClick={onClose}/></header>
    <label className={s.searchBox}><Icon name="search" size={16}/><input aria-label={`搜索${title}`} placeholder={kind==='tools'?'搜索工具，例如「背景」':'搜索素材名称'} value={search} onChange={e=>setSearch(e.target.value)}/></label>
    {kind==='tools'?<><div className={s.categoryTabs}>{CATEGORIES.map(c=><button type="button" key={c} className={category===c?s.categoryActive:''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className={s.drawerScroll}>{CATEGORIES.slice(1).filter(c=>category==='全部'||c===category).map(c=>{const tools=TOOLS.filter(t=>t.category===c&&(t.name+t.description).includes(search));return tools.length?<section className={s.toolCategory} key={c}><h3>{c}</h3>{tools.map(tool=><button type="button" className={s.toolRow} key={tool.id} onClick={()=>onTool(tool.id)}><span className={s.toolRowIcon}><Icon name={tool.icon} size={20}/></span><span><strong>{tool.name}</strong><small>{tool.description}</small></span><Icon name="next" size={14}/></button>)}</section>:null})}</div><footer className={s.drawerFooter}><Icon name="sparkles" size={13}/>完整工具规划 · AI 能力为演示</footer></>:kind==='layers'?<div className={s.drawerScroll}>{[...studio.doc.nodes].reverse().filter(n=>n.name.includes(search)).map(n=><div key={n.id} className={`${s.layerRow} ${studio.selected.includes(n.id)?s.layerSelected:''}`}><button type="button" onClick={()=>studio.select([n.id])}>{n.kind==='image'?<Picture url={n.url} name={n.name}/>:<Icon name="text"/>}<span>{n.name}<small>{n.group??'未分组'}</small></span></button><IconButton label={`定位 ${n.name}`} icon="focus" onClick={()=>onFocus([n.id])}/></div>)}</div>:<><div className={s.categoryTabs}>{['本项目','服装成片','姿势','收藏'].map(tab=><button type="button" key={tab} className={assetTab===tab?s.categoryActive:''} onClick={()=>setAssetTab(tab)}>{tab}</button>)}</div><div className={s.drawerScroll}><button type="button" className={s.uploadArea} onClick={onUpload}><Icon name="upload" size={20}/><strong>导入自己的图片</strong><span>JPG / PNG / WebP · 每张不超过 20MB</span></button><div className={s.assetGrid}>{filtered.map(node=><article className={s.assetCard} key={node.id}><button type="button" className={s.assetPreview} onClick={()=>onAsset(node,false)} aria-label={`放入画布 ${node.name}`}><Picture url={node.url} name={node.name}/></button><strong>{node.name}</strong><div><button type="button" onClick={()=>onAsset(node,false)}>放入画布</button><button type="button" onClick={()=>onAsset(node,true)}>用作参考<Icon name="plus" size={12}/></button></div></article>)}</div>{!filtered.length&&<p className={s.emptyList}>这里还没有素材，先从画布中收藏一张。</p>}</div></>}
  </section>
}
