import type { PoseTemplate } from './types'

/**
 * 姿势裂变姿势模板种子数据。
 *
 * 由 scripts/seed-pose-templates.ts 从友商资料按关键词分桶筛选生成，
 * 图片已下载到 public/poses/<id>.jpg。
 *
 * 修改请直接重跑脚本，不要手改本文件（除非临时调整 prompt 文案）。
 */
export const POSE_TEMPLATES_SEED: PoseTemplate[] = [
  {
    id: 'pose-front-stand-1',
    name: '正面站姿1',
    imageUrl: '/poses/pose-front-stand-1-imagegen.png',
    prompt: '女模特身材高挑纤细，以正面站姿朝向镜头，双脚自然分开，穿着这套服装，她左手扶腰，右臂自然下垂握这个包，头部微抬，目光平静直视镜头，表情清冷松弛。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-front-stand-2',
    name: '正面站姿2',
    imageUrl: '/poses/pose-front-stand-2-imagegen.png',
    prompt: '姿态呈现静态肖像场景。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-front-stand-3',
    name: '正面站姿3',
    imageUrl: '/poses/pose-front-stand-3-imagegen.png',
    prompt: '姿态放松自然，背景中的城市街道、栏杆及车辆形成场景呼应。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-front-stand-4',
    name: '正面站姿4',
    imageUrl: '/poses/pose-front-stand-4-imagegen.png',
    prompt: '人物以直立站姿站立，双腿自然分开与肩同宽，双手插于裤口袋（双手完全入袋，手臂自然下垂，肘部微弯）；头部微侧（视线看向镜头方向，颈部挺直无僵硬感）。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-side-stand-1',
    name: '侧身站姿1',
    imageUrl: '/poses/pose-side-stand-1-imagegen.png',
    prompt: '姿态自然放松，侧身倚靠在一辆白色复古轿车的后车门上，前车门呈现打开状态，遮挡了人物部分身体，一只手轻触下巴，一手插在口袋中，头微微底下，目光低垂，流露出沉思或优雅的气质。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-side-stand-2',
    name: '侧身站姿2',
    imageUrl: '/poses/pose-side-stand-2-imagegen.png',
    prompt: '姿态放松，目光直视前方。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-side-stand-3',
    name: '侧身站姿3',
    imageUrl: '/poses/pose-side-stand-3-imagegen.png',
    prompt: '男模特（留着微卷短发），侧身倚靠在白色栏杆的船舷处，右胳膊搭在栏杆上，左手插在口袋里，眼神看向画面左侧。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-side-stand-4',
    name: '侧身站姿4',
    imageUrl: '/poses/pose-side-stand-4-imagegen.png',
    prompt: '姿态放松地侧身倚靠门框，左手持浅棕色纸杯（类似爆米花桶），右手轻拿里面的爆米花，颜色看向画面左侧，背景电梯门内隐约可见绿色植物，大部分植物都被人物遮挡住。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-walking-1',
    name: '行走姿1',
    imageUrl: '/poses/pose-walking-1-imagegen.png',
    prompt: '姿态，抓拍；整体用自然写实风格，浅景深虚化背景。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-walking-2',
    name: '行走姿2',
    imageUrl: '/poses/pose-walking-2-imagegen.png',
    prompt: '女模特身材高挑纤细，朝画面的左侧45度方向行走，行走抓拍。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-walking-3',
    name: '行走姿3',
    imageUrl: '/poses/pose-walking-3-imagegen.png',
    prompt: '模特都处于实焦范围，细节清晰；玻璃窗外的户外绿植、走廊尽头的墙面则做了适度虚化，既保留了室内外的通透感，又牢牢将视觉重心锚定在人物与核心空间区域。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-walking-4',
    name: '行走姿4',
    imageUrl: '/poses/pose-walking-4-imagegen.png',
    prompt: '女模特身材高挑纤细，完全以背面向镜头，正沿着黑色栈道向前行走：右脚稳稳踩在木质板面，左脚抬起处于迈步的动态瞬间，头部微微低垂，黑发低发髻，状态慵懒随性。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-sitting-1',
    name: '坐姿1',
    imageUrl: '/poses/pose-sitting-1-imagegen.png',
    prompt: '姿态放松，双腿自然交叠，一只手搭在腿上，另一只手轻放，神情从容。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-sitting-2',
    name: '坐姿2',
    imageUrl: '/poses/pose-sitting-2-imagegen.png',
    prompt: '姿态放松，左臂自然搭在座椅上，右腿交叠左腿，身体重心偏向右侧。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-sitting-3',
    name: '坐姿3',
    imageUrl: '/poses/pose-sitting-3-imagegen.png',
    prompt: '姿态放松自然，身穿这个服装，右手抬起轻抛黄色网球，左手自然搭在长椅上，眼神看向镜头，身旁及地上散落着两颗黄色网球，背景是网球场的红土橡胶地面，远处是铁丝网的围栏，后方可见浅灰色带绿色窗框的建筑。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-sitting-4',
    name: '坐姿4',
    imageUrl: '/poses/pose-sitting-4-imagegen.png',
    prompt: '姿态放松；右侧的年轻欧美女士则坐在木质码头边缘的金属扶梯上，身着图一的服装，一条腿浸于清澈的水中，侧身转头望向男士，神情柔和。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-crouching-1',
    name: '蹲姿1',
    imageUrl: '/poses/pose-crouching-1-imagegen.png',
    prompt: '姿态端正；身着这套服装，头戴这个帽子，眼神专注侧视左侧，身体朝向左侧45度，头部微抬。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-crouching-2',
    name: '蹲姿2',
    imageUrl: '/poses/pose-crouching-2-imagegen.png',
    prompt: '姿态放松，一手肘撑在膝盖上，一手轻托脸颊，肢体自然弯曲，屈膝蹲在在泳池边缘（背景是蓝绿色瓷砖铺就的泳池水域，池边有浅色石质或木质结构，远处隐约可见绿色植被与浅色墙面）。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-crouching-3',
    name: '蹲姿3',
    imageUrl: '/poses/pose-crouching-3-imagegen.png',
    prompt: '姿态亲昵在画面中央偏下的位置，女性穿着图一服装，小男孩穿着图二服装，带着这个墨镜，微笑看着女性，二人姿态亲昵——女性半蹲侧身，手轻扶孩子，孩子坐姿乖巧。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-back-turn-1',
    name: '回头侧脸1',
    imageUrl: '/poses/pose-back-turn-1-imagegen.png',
    prompt: '姿态自然地踏在岩石上，右手抓住岩石，左手自然垂落，身体微微侧身，转头眼神看向镜头，展现出户外探索的活力感。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-back-turn-2',
    name: '回头侧脸2',
    imageUrl: '/poses/pose-back-turn-2-imagegen.png',
    prompt: '伦敦街道平视角（与狗等高）拍摄，这三只犬背对镜头坐姿放松，左侧这只犬穿这套服装（图4），回头看向镜头，中间这只犬穿这套服装（图6），右侧这只犬穿这套服装（图5），头微转向左侧；犬坐成一排，靠近。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-back-turn-3',
    name: '回头侧脸3',
    imageUrl: '/poses/pose-back-turn-3-imagegen.png',
    prompt: '姿态松弛淡然，穿着这套服装。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'full',
  },
  {
    id: 'pose-hands-pocket-1',
    name: '手插口袋1',
    imageUrl: '/poses/pose-hands-pocket-1-imagegen.png',
    prompt: '主体是一位年轻中国男性，站在画面中间偏右的位置，靠在墙上，采用全身平视视角，画面为竖幅构图，整体布局对称且富有秩序感。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'upper',
  },
  {
    id: 'pose-hands-pocket-2',
    name: '手插口袋2',
    imageUrl: '/poses/pose-hands-pocket-2-imagegen.png',
    prompt: '姿态自然放松，一手插在裤袋中，一手自然垂落，头微微向左靠，一腿微微弯曲。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'upper',
  },
  {
    id: 'pose-hands-pocket-3',
    name: '手插口袋3',
    imageUrl: '/poses/pose-hands-pocket-3-imagegen.png',
    prompt: '主体人物位于画面中央位置，采用全身特写视角，展现其站立于水边岩石上的姿态。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'upper',
  },
  {
    id: 'pose-arms-crossed-1',
    name: '抱胸1',
    imageUrl: '/poses/pose-arms-crossed-1-imagegen.png',
    prompt: '姿态，双臂交叉环抱于胸前，头部向后微扬，双眼闭合、下颌抬高，正放松地仰头感受落在脸上的日光，神态舒展恬淡，清冷气质和场景契合度极高。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'upper',
  },
  {
    id: 'pose-arms-crossed-2',
    name: '抱胸2',
    imageUrl: '/poses/pose-arms-crossed-2-imagegen.png',
    prompt: '姿态呈现，身体躯干略微向镜头左侧倾斜，头部却正对着镜头方向，眼神明亮且专注地看向镜头，嘴角上扬露出微笑，传递出轻松愉悦的情绪。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'upper',
  },
  {
    id: 'pose-arms-crossed-3',
    name: '抱胸3',
    imageUrl: '/poses/pose-arms-crossed-3-imagegen.png',
    prompt: '姿态呈现，左手轻搭在白色栏杆上，右手环抱住怀中的宠物，身体略微转向镜头方向，头部微微转向并看向镜头，眼睛明亮有神，嘴角上扬露出温柔的微笑，神情轻松愉悦。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'upper',
  },
  {
    id: 'pose-touch-face-1',
    name: '抚面1',
    imageUrl: '/poses/pose-touch-face-1-imagegen.png',
    prompt: '模特穿着这个服装，身体半趴在桌面上，左手肘部支撑桌面，右手托着脸颊，左手拿着一颗黄色的柠檬靠近嘴部，眼神看向画面右侧，姿态慵懒而放松。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'upper',
  },
  {
    id: 'pose-touch-face-2',
    name: '抚面2',
    imageUrl: '/poses/pose-touch-face-2-imagegen.png',
    prompt: '女网红身着这个服装，左手抬起轻轻抚摸发丝，右手提这个包。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'upper',
  },
  {
    id: 'pose-touch-face-3',
    name: '抚面3',
    imageUrl: '/poses/pose-touch-face-3-imagegen.png',
    prompt: '姿态放松地坐在沙发上，前爪平稳放置于沙发表面，身体转向左侧，与模特动作方向一致，显示出亲密的互动状态。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'upper',
  },
  {
    id: 'pose-leg-up-1',
    name: '抬腿1',
    imageUrl: '/poses/pose-leg-up-1-imagegen.png',
    prompt: '姿态轻松自然，左腿抬起踩在船舷金属栏杆上（镜头在栏杆前拍摄），右手轻扶船绳，左手自然垂落，发丝微湿带点凌乱感，眼神放松，整体造型充满青春活力与休闲度假氛围。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'lower',
  },
  {
    id: 'pose-leg-up-2',
    name: '抬腿2',
    imageUrl: '/poses/pose-leg-up-2-imagegen.png',
    prompt: '女模特身材高挑纤细，穿着这套服装，坐在红色木质长椅左侧，右手高举挥手（手掌张开），双腿屈膝脚踩在椅子上，身体放松倚靠椅背，闭眼微笑，表情柔和。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'lower',
  },
  {
    id: 'pose-leg-up-3',
    name: '抬腿3',
    imageUrl: '/poses/pose-leg-up-3-imagegen.png',
    prompt: '女模特与这位男孩并肩站立，以活泼的姿势和明亮的色彩传递出轻松可爱的氛围。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'lower',
  },
  {
    id: 'pose-cross-step-1',
    name: '交叉腿1',
    imageUrl: '/poses/pose-cross-step-1-imagegen.png',
    prompt: '姿态舒展自然：她双腿交叉站立，右臂弯曲扶着挎在左臂的这个包的包带，左手抬起轻触颈间的长款项链，头部转向左侧望向窗边方向，神情平静从容，没有刻意的摆拍感。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'lower',
  },
  {
    id: 'pose-cross-step-2',
    name: '交叉腿2',
    imageUrl: '/poses/pose-cross-step-2-imagegen.png',
    prompt: '姿态放松，身着这套服装。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'lower',
  },
  {
    id: 'pose-cross-step-3',
    name: '交叉腿3',
    imageUrl: '/poses/pose-cross-step-3-imagegen.png',
    prompt: '环境与空间细节： 场景设定在一个充满原始感的室外。背景是一面巨大的白色灰泥墙面，带有不规则的自然裂纹和粗粝的磨砂肌理。环境光线由强烈的自然日光组成，在墙面上投射出边缘锐利、斑驳的树影。地面是干燥且质感。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'lower',
  },
  {
    id: 'pose-lean-1',
    name: '倚靠1',
    imageUrl: '/poses/pose-lean-1-imagegen.png',
    prompt: '姿态自然放松，双手插兜靠在墙上，背景为深棕色木质墙面与木质家具，左侧有一台深灰色的追觅科技产品（可能是风扇或吸尘器），右侧是带有抽屉的木质矮柜，柜上放置书籍、红色杯具。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'lower',
  },
  {
    id: 'pose-lean-2',
    name: '倚靠2',
    imageUrl: '/poses/pose-lean-2-imagegen.png',
    prompt: '人物姿态放松，右手插在裤袋，左手自然垂落，倚靠在墙面上。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'lower',
  },
  {
    id: 'pose-lean-3',
    name: '倚靠3',
    imageUrl: '/poses/pose-lean-3-imagegen.png',
    prompt: '主体是一位年轻中国男网红，采用三分法构图，人物居中偏下，上半身及手臂自然倚靠在平台边缘，姿态放松。保持原服装与人物身份不变。',
    ageGroup: 'adult',
    bodyPart: 'lower',
  },
  {
    id: 'pose-kid-stand-1',
    name: '儿童站姿1',
    imageUrl: '/poses/pose-kid-stand-1-imagegen.png',
    prompt: '姿态自然生动：侧身 45° 行走，头转向镜头，微笑，身材高挑纤细，左手自然摆动轻抬，右手与小男孩牵手；上半身挺直，穿着这套服装，整体造型清新利落，笑容明媚。保持原服装与人物身份不变。',
    ageGroup: 'kid',
    bodyPart: 'full',
  },
  {
    id: 'pose-kid-stand-2',
    name: '儿童站姿2',
    imageUrl: '/poses/pose-kid-stand-2-imagegen.png',
    prompt: '姿态放松；右侧小女孩双手举至脸部调整这副墨镜，嘴角上扬露齿笑，穿着这套服装。保持原服装与人物身份不变。',
    ageGroup: 'kid',
    bodyPart: 'full',
  },
  {
    id: 'pose-kid-stand-3',
    name: '儿童站姿3',
    imageUrl: '/poses/pose-kid-stand-3-imagegen.png',
    prompt: '镜头采用仰拍角度捕捉行走动态，背景石墙清晰、左侧建筑虚化，小景深突出主体；暖白色调滤镜弱化色彩对比，光线柔和明亮，整体画面温馨优雅，完美诠释亲子装的高级质感与日常互动的幸福氛围。保持原服装与人物身份不变。',
    ageGroup: 'kid',
    bodyPart: 'full',
  },
  {
    id: 'pose-kid-action-1',
    name: '儿童动态1',
    imageUrl: '/poses/pose-kid-action-1-imagegen.png',
    prompt: '姿态自然；右侧这位女模特身材高挑纤细，穿着这套服装，双腿分开站立（一前一后），面带笑意。保持原服装与人物身份不变。',
    ageGroup: 'kid',
    bodyPart: 'full',
  },
  {
    id: 'pose-kid-action-2',
    name: '儿童动态2',
    imageUrl: '/poses/pose-kid-action-2-imagegen.png',
    prompt: '她左手提这个包、右手自然抬起，姿态随性不羁。保持原服装与人物身份不变。',
    ageGroup: 'kid',
    bodyPart: 'full',
  },
]

/**
 * 「基础搭配 3 张」一键预设的姿势模板 id 集合（PRD D8）。
 * 优先选正面站姿/侧身站姿/行走姿。
 */
export const POSE_TEMPLATES_DEFAULT_TRIO_SEED: string[] = [
  'pose-front-stand-1',
  'pose-side-stand-1',
  'pose-walking-1',
]

/**
 * POSE_FISSION_CASES[0] 引用的 6 个 templateId（黑色蕾丝裙 6 姿势套图）。
 * 仅保证 id 存在于 POSE_TEMPLATES_SEED 中。
 */
export const POSE_FISSION_CASE_BLACK_DRESS_TEMPLATE_IDS_SEED: string[] = [
  'pose-front-stand-1',
  'pose-side-stand-1',
  'pose-walking-1',
  'pose-back-turn-1',
  'pose-sitting-1',
  'pose-crouching-1',
]
